// modalsName libs
export const BILLBOARD_MODAL = "BILLBOARD_MODAL";
export const CLOSED_BILLBOARD_MODAL = "CLOSED_BILLBOARD_MODAL";
export const MAIN_MENU = "MAIN_MENU";
export const CONFIRM_CHANGES = "CONFIRM_CHANGES";
export const CONFIRM_ENTRY_DAILY = "CONFIRM_ENTRY_DAILY";
export const MOJE_CALCULATE = "MOJE_CALCULATE";
export const MORE_ACTIONS_MENU = "MORE_ACTIONS_MENU";
export const CONFIRM_REGISTER_SHIFT_MODAL = "CONFIRM_REGISTER_SHIFT_MODAL";
export const EXCEPTION_MESSAGES_MODAL = "EXCEPTION_MESSAGES_MODAL";
export const EXCEPTION_MESSAGES_CASHIER_SESSION_MODAL =
  "EXCEPTION_MESSAGES_MODAL";

// Main menu
export const OPEN_CASHIER_SESSION = "OPEN_CASHIER_SESSION"; // Apertura de caja
export const DISABLED_PRODUCTS = "DISABLED_PRODUCTS";
export const CLOSE_CASHIER_SESSION = "CLOSE_CASHIER_SESSION";
export const CASH_OUT_PROCESS = "CASH_OUT_PROCESS";
export const CLOSE_OPERATIONS_PERIOD = "CLOSE_OPERATIONS_PERIOD";

// ORDER LIBS
export const ADD_MODIFIER_MODAL = "ADD_MODIFIER_MODAL";
