export const BILL_NAME = "BILL_NAME";
export const NOTES_NAME = "NOTES_NAME";
export const COMMENTS = "COMMENTS";
export const SEPARATE_CHECKS = "SEPARATE_CHECKS";
export const MOVE_PRODUCTS = "MOVE_PRODUCTS";
export const MOVE_TABLE = "MOVE_TABLE";
export const PRODUCTS_DISCOUNTS = "PRODUCTS_DISCOUNTS";
export const NOTES_DISCOUNTS = "NOTES_DISCOUNTS";
export const BILL_DISCOUNTS = "BILL_DISCOUNTS";
export const COURTESY_APPLY_PRODUCTS = "COURTESY_APPLY_PRODUCTS";
export const COURTESY_APPLY_NOTES = "COURTESY_APPLY_NOTES";
export const COURTESY_APPLY_BILL = "COURTESY_APPLY_BILL";
export const PRODUCTS_CANCEL = "PRODUCTS_CANCEL";
export const NOTES_CANCEL = "NOTES_CANCEL";
export const BILL_CANCEL = "BILL_CANCEL";

// ACA SEGUIREMOS CON TODO LE PROCESO PARA ACTIOVAR OPCIONES EN TIPO   TO_GO_ORDER

export const TO_GO_PAYMENT = "TO_GO_PAYMENT";
export const TO_GO_NAME_ORDER = "TO_GO_NAME_ORDER";
export const TO_GO_COMMENT = "TO_GO_COMMENT";
export const TO_GO_DISCOUNT_PRODUCT = "TO_GO_DISCOUNT_PRODUCT";
export const TO_GO_DISCOUNT_ORDER = "TO_GO_DISCOUNT_ORDER";
export const TO_GO_COURTESY_PRODUCT = "TO_GO_COURTESY_PRODUCT";
export const TO_GO_COURTESY_ORDER = "TO_GO_COURTESY_ORDER";
export const TO_GO_CANCEL_ORDER = "TO_GO_CANCEL_ORDER";
export const TO_GO_REPRINT_ORDER = "TO_GO_REPRINT_ORDER";
