export const reports = [
  { reportName: "Cuentas canceladas", status: true },
  { reportName: "Notas canceladas", status: true },
  { reportName: "Productos cancelados", status: true },
  { reportName: "Cuentas abiertas", status: true },
  { reportName: "Cuentas pagadas", status: true },
  { reportName: "Cuentas reabiertas", status: true },
  { reportName: "Cuentas reimpresas", status: true },
  { reportName: "Descuentos en cuentas", status: true },
  { reportName: "Descuentos en notas", status: true },
  { reportName: "Descuentos en productos", status: true },
  { reportName: "Descuentos descontinuados", status: true },
  { reportName: "Rotacion de mesas", status: true },
  { reportName: "Tiempo de estatus en espera", status: true },
  { reportName: "Tiempo de estatus activa", status: true },
  { reportName: "Tiempo de estatus por pagar", status: true },
  { reportName: "Transferencia de cuentas", status: true },
  { reportName: "Transferencia de productos", status: true },
  { reportName: "Apertura de caja", status: true },
];
